INSERT INTO ACEG_ROLE (ROLE_PK, DESCRIPCION) VALUES ('ADMINISTRADOR','ADMINISTRADOR DE LA APLICACION');
INSERT INTO ACEG_ROLE (ROLE_PK, DESCRIPCION) VALUES ('CARNICERO','USUARIO DE TIPO CARNICERO');
INSERT INTO ACEG_ROLE (ROLE_PK, DESCRIPCION) VALUES ('CLIENTE','USUARIO DE TIPO CLIENTE');
INSERT INTO ACEG_ROLE (ROLE_PK, DESCRIPCION) VALUES ('PROVEEDOR','USUARIO DE TIPO PROVEEDOR');