INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Aguascalientes', 'AGU');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Baja California', 'BCN');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Baja California Sur', 'BCS');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Campeche', 'CAM');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Chiapas', 'CHP');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Chihuahua', 'CHH');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Ciudad de México ', 'CMX');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Coahuila', 'COA');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Colima', 'COL');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Durango', 'DUR');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Guanajuato', 'GUA');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Guerrero', 'GRO');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Hidalgo', 'HID');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Jalisco', 'JAL');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('México', 'MEX');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Michoacán', 'MIC');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Morelos', 'MOR');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Nayarit', 'NAY');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Nuevo León', 'NLE');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Oaxaca ', 'OAX');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Puebla ', 'PUE');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Querétaro ', 'QUE');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Quintana Roo ', 'ROO');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('San Luis Potosí ', 'SLP');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Sinaloa ', 'SIN');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Sonora ', 'SON');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Tabasco ', 'TAB');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Tamaulipas ', 'TAM');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Tlaxcala ', 'TLA');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Veracruz ', 'VER');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Yucatán ', 'YUC');
INSERT INTO ESTADO (ESTADO, ABREVIACION)
VALUES ('Zacatecas ', 'ZAC');