-- PERMISOS DEL USUARIO
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER alejandro IDENTIFIED BY carniceriaelguero;
GRANT ALL PRIVILEGES TO alejandro;
GRANT
    EXECUTE ANY PROCEDURE
TO alejandro;
GRANT
    UNLIMITED TABLESPACE
TO alejandro;

-- TABLAS
DROP TABLE CARN_PROD_CARN;
DROP TABLE CARNICERIA_CLIENTE;
DROP TABLE MUNICIPIO;
DROP TABLE PROD_CAR_PED;
DROP TABLE PROD_CAR_PRO_ADE_CLI;
DROP TABLE PROD_CARNICERIA;
DROP TABLE PROD_PROV_NOTA_ADE;
DROP TABLE PROD_PROV_NOTA_PAG;
DROP TABLE PROV_PROD_PROV;
DROP TABLE PROVEEDOR_CARNICERIA;
DROP TABLE NOTA_ADEUDADA;
DROP TABLE NOTA_PAGADA;
DROP TABLE PEDIDO;
DROP TABLE PROD_ADE_CLIENTE;
DROP TABLE PROD_PROVEEDOR;
DROP TABLE PROVEEDOR;
DROP TABLE CARNICERO;
DROP TABLE CLIENTE;
DROP TABLE CARNICERIA;
DROP TABLE ESTADO;
DROP TABLE NOMBRE_TABLA CASCADE CONSTRAINTS;


-- Generado por Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   en:        2020-08-20 17:57:22 CDT
--   sitio:      Oracle Database 12c
--   tipo:      Oracle Database 12c
-- predefined type, no DDL - MDSYS.SDO_GEOMETRY
-- predefined type, no DDL - XMLTYPE

CREATE TABLE carn_prod_carn (
    carniceria_id        NUMBER NOT NULL,
    prod_carniceria_id   NUMBER NOT NULL
);

ALTER TABLE carn_prod_carn ADD CONSTRAINT carn_prod_carn_pk PRIMARY KEY ( carniceria_id,
                                                                          prod_carniceria_id );

CREATE TABLE carniceria (
    id              NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    direccion       VARCHAR2(100),
    codigo_postal   VARCHAR2(5),
    telefono        CHAR(10),
    descripcion     VARCHAR2(100),
    estado_id       NUMBER NOT NULL
);

ALTER TABLE carniceria ADD CONSTRAINT carniceria_pk PRIMARY KEY ( id );

CREATE TABLE carniceria_cliente (
    cliente_id      NUMBER NOT NULL,
    carniceria_id   NUMBER NOT NULL
);

ALTER TABLE carniceria_cliente ADD CONSTRAINT carniceria_cliente_pk PRIMARY KEY ( cliente_id,
                                                                                  carniceria_id );

CREATE TABLE carnicero (
    id               NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    nombre           VARCHAR2(30) NOT NULL,
    apellido         VARCHAR2(50),
    genero           CHAR(1),
    email            VARCHAR2(30),
    telefono         CHAR(10) NOT NULL,
    direccion        VARCHAR2(100),
    codigo_postal    CHAR(5),
    sueldo_mensual   NUMBER(7, 2) NOT NULL,
    carniceria_id    NUMBER NOT NULL,
    estado_id        NUMBER NOT NULL
);

ALTER TABLE carnicero ADD CONSTRAINT carnicero_pk PRIMARY KEY ( id,
                                                                carniceria_id );

CREATE TABLE cliente (
    id              NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    nombre          VARCHAR2(30) NOT NULL,
    apellido        VARCHAR2(50),
    genero          CHAR(1),
    email           VARCHAR2(30),
    telefono        CHAR(10),
    direccion       VARCHAR2(100),
    codigo_postal   CHAR(5),
    estado_id       NUMBER NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id );

CREATE TABLE estado (
    id            NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    estado        VARCHAR2(50) NOT NULL,
    abreviacion   CHAR(3)
);

ALTER TABLE estado ADD CONSTRAINT estado_pk PRIMARY KEY ( id );

CREATE TABLE municipio (
    id          NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    municipio   VARCHAR2(50) NOT NULL,
    estado_id   NUMBER NOT NULL
);

ALTER TABLE municipio ADD CONSTRAINT municipio_pk PRIMARY KEY ( id );

CREATE TABLE nota_adeudada (
    id                        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    id_nota                   NUMBER NOT NULL,
    fecha_compra              DATE NOT NULL,
    peso_producto             VARCHAR2(10) NOT NULL,
    total                     NUMBER(7, 2) NOT NULL,
    descripcion               VARCHAR2(100),
    carnicero_id              NUMBER NOT NULL,
    carnicero_carniceria_id   NUMBER NOT NULL
);

ALTER TABLE nota_adeudada ADD CONSTRAINT nota_adeudada_pk PRIMARY KEY ( id,
                                                                        id_nota );

CREATE TABLE nota_pagada (
    id                        NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    id_nota                   NUMBER NOT NULL,
    fecha_compra_producto     DATE NOT NULL,
    fecha_paga_producto       DATE NOT NULL,
    peso_producto             VARCHAR2(10) NOT NULL,
    total                     NUMBER(7, 5) NOT NULL,
    descripcion               VARCHAR2(100),
    carnicero_id              NUMBER NOT NULL,
    carnicero_carniceria_id   NUMBER NOT NULL
);

ALTER TABLE nota_pagada ADD CONSTRAINT nota_pagada_pk PRIMARY KEY ( id_nota,
                                                                    id );

CREATE TABLE pedido (
    id              NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    id_pedido       NUMBER NOT NULL,
    peso_total_kg   NUMBER(7, 2) NOT NULL,
    fecha_entrega   DATE NOT NULL,
    total           NUMBER(7, 2) NOT NULL,
    descripcion     VARCHAR2(100),
    carniceria_id   NUMBER NOT NULL,
    cliente_id      NUMBER NOT NULL
);

ALTER TABLE pedido
    ADD CONSTRAINT pedido_pk PRIMARY KEY ( id,
                                           carniceria_id,
                                           cliente_id,
                                           id_pedido );

CREATE TABLE prod_ade_cliente (
    id              NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    fecha_compra    DATE NOT NULL,
    peso_producto   NUMBER(7, 2) NOT NULL,
    total           NUMBER(7, 2) NOT NULL,
    descripcion     VARCHAR2(100),
    cliente_id      NUMBER NOT NULL
);

ALTER TABLE prod_ade_cliente ADD CONSTRAINT prod_ade_cliente_pk PRIMARY KEY ( id,
                                                                              cliente_id );

CREATE TABLE prod_car_ped (
    prod_carniceria_id     NUMBER NOT NULL,
    pedido_id              NUMBER NOT NULL,
    pedido_carniceria_id   NUMBER NOT NULL,
    pedido_cliente_id      NUMBER NOT NULL,
    pedido_id_pedido       NUMBER NOT NULL
);

ALTER TABLE prod_car_ped
    ADD CONSTRAINT prod_car_ped_pk PRIMARY KEY ( prod_carniceria_id,
                                                 pedido_id,
                                                 pedido_carniceria_id,
                                                 pedido_cliente_id,
                                                 pedido_id_pedido );

CREATE TABLE prod_car_pro_ade_cli (
    prod_ade_cliente_id           NUMBER NOT NULL,
    prod_ade_cliente_cliente_id   NUMBER NOT NULL,
    prod_carniceria_id            NUMBER NOT NULL
);

ALTER TABLE prod_car_pro_ade_cli
    ADD CONSTRAINT prod_car_pro_ade_cli_pk PRIMARY KEY ( prod_ade_cliente_id,
                                                         prod_ade_cliente_cliente_id,
                                                         prod_carniceria_id );

CREATE TABLE prod_carniceria (
    id            NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    producto      VARCHAR2(50) NOT NULL,
    precio_kg     NUMBER(7, 2) NOT NULL,
    tipo_carne    VARCHAR2(5) NOT NULL,
    descripcion   VARCHAR2(100)
);

ALTER TABLE prod_carniceria ADD CONSTRAINT prod_carniceria_pk PRIMARY KEY ( id );

CREATE TABLE prod_prov_nota_ade (
    nota_adeudada_id        NUMBER NOT NULL,
    nota_adeudada_id_nota   NUMBER NOT NULL,
    prod_proveedor_id       NUMBER NOT NULL
);

ALTER TABLE prod_prov_nota_ade
    ADD CONSTRAINT prod_prov_nota_ade_pk PRIMARY KEY ( nota_adeudada_id,
                                                       nota_adeudada_id_nota,
                                                       prod_proveedor_id );

CREATE TABLE prod_prov_nota_pag (
    nota_pagada_id_nota   NUMBER NOT NULL,
    nota_pagada_id        NUMBER NOT NULL,
    prod_proveedor_id     NUMBER NOT NULL
);

ALTER TABLE prod_prov_nota_pag
    ADD CONSTRAINT prod_prov_nota_pag_pk PRIMARY KEY ( nota_pagada_id_nota,
                                                       nota_pagada_id,
                                                       prod_proveedor_id );

CREATE TABLE prod_proveedor (
    id            NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    producto      VARCHAR2(30) NOT NULL,
    precio_kg     NUMBER(7, 2) NOT NULL,
    tipo_carne    VARCHAR2(5) NOT NULL,
    descripcion   VARCHAR2(100)
);

ALTER TABLE prod_proveedor ADD CONSTRAINT prod_proveedor_pk PRIMARY KEY ( id );

CREATE TABLE prov_prod_prov (
    proveedor_id        NUMBER NOT NULL,
    prod_proveedor_id   NUMBER NOT NULL
);

ALTER TABLE prov_prod_prov ADD CONSTRAINT prov_prod_prov_pk PRIMARY KEY ( proveedor_id,
                                                                          prod_proveedor_id );

CREATE TABLE proveedor (
    id                 NUMBER
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1
    NOT NULL,
    nombre_empresa     VARCHAR2(30),
    nombre_proveedor   VARCHAR2(30) NOT NULL,
    apellido           VARCHAR2(50),
    genero             CHAR(1),
    email              VARCHAR2(50),
    telefono           CHAR(10) NOT NULL,
    direccion          VARCHAR2(100),
    codigo_postal      CHAR(5)
);

ALTER TABLE proveedor ADD CONSTRAINT proveedor_pk PRIMARY KEY ( id );

CREATE TABLE proveedor_carniceria (
    proveedor_id    NUMBER NOT NULL,
    carniceria_id   NUMBER NOT NULL
);

ALTER TABLE proveedor_carniceria ADD CONSTRAINT proveedor_carniceria_pk PRIMARY KEY ( proveedor_id,
                                                                                      carniceria_id );

-- LLAVES FORANEAS 

ALTER TABLE carn_prod_carn
    ADD CONSTRAINT carn_prod_carn_carniceria_fk FOREIGN KEY ( carniceria_id )
        REFERENCES carniceria ( id );

ALTER TABLE carn_prod_carn
    ADD CONSTRAINT carn_prod_carn_prod_carn_fk FOREIGN KEY ( prod_carniceria_id )
        REFERENCES prod_carniceria ( id );

ALTER TABLE carniceria_cliente
    ADD CONSTRAINT carn_cliente_carn_fk FOREIGN KEY ( carniceria_id )
        REFERENCES carniceria ( id );

ALTER TABLE carniceria_cliente
    ADD CONSTRAINT carniceria_cliente_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( id );

ALTER TABLE carniceria
    ADD CONSTRAINT carniceria_estado_fk FOREIGN KEY ( estado_id )
        REFERENCES estado ( id );

ALTER TABLE carnicero
    ADD CONSTRAINT carnicero_carniceria_fk FOREIGN KEY ( carniceria_id )
        REFERENCES carniceria ( id );

ALTER TABLE carnicero
    ADD CONSTRAINT carnicero_estado_fk FOREIGN KEY ( estado_id )
        REFERENCES estado ( id );

ALTER TABLE cliente
    ADD CONSTRAINT cliente_estado_fk FOREIGN KEY ( estado_id )
        REFERENCES estado ( id );

ALTER TABLE municipio
    ADD CONSTRAINT municipio_estado_fk FOREIGN KEY ( estado_id )
        REFERENCES estado ( id );

ALTER TABLE nota_adeudada
    ADD CONSTRAINT nota_adeudada_carnicero_fk FOREIGN KEY ( carnicero_id,
                                                            carnicero_carniceria_id )
        REFERENCES carnicero ( id,
                               carniceria_id );

ALTER TABLE nota_pagada
    ADD CONSTRAINT nota_pagada_carnicero_fk FOREIGN KEY ( carnicero_id,
                                                          carnicero_carniceria_id )
        REFERENCES carnicero ( id,
                               carniceria_id );

ALTER TABLE pedido
    ADD CONSTRAINT pedido_carniceria_fk FOREIGN KEY ( carniceria_id )
        REFERENCES carniceria ( id );

ALTER TABLE pedido
    ADD CONSTRAINT pedido_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( id );

ALTER TABLE prod_ade_cliente
    ADD CONSTRAINT prod_ade_cliente_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( id );

ALTER TABLE prod_car_ped
    ADD CONSTRAINT prod_car_ped_pedido_fk FOREIGN KEY ( pedido_id,
                                                        pedido_carniceria_id,
                                                        pedido_cliente_id,
                                                        pedido_id_pedido )
        REFERENCES pedido ( id,
                            carniceria_id,
                            cliente_id,
                            id_pedido );

ALTER TABLE prod_car_ped
    ADD CONSTRAINT prod_car_ped_prod_carn_fk FOREIGN KEY ( prod_carniceria_id )
        REFERENCES prod_carniceria ( id );

ALTER TABLE prod_car_pro_ade_cli
    ADD CONSTRAINT prod_car_pro_ade_cli_fk FOREIGN KEY ( prod_ade_cliente_id,
                                                                          prod_ade_cliente_cliente_id )
        REFERENCES prod_ade_cliente ( id,
                                      cliente_id );

ALTER TABLE prod_car_pro_ade_cli
    ADD CONSTRAINT prod_car_pro_cli_prod_carn_fk FOREIGN KEY ( prod_carniceria_id )
        REFERENCES prod_carniceria ( id );

ALTER TABLE prod_prov_nota_ade
    ADD CONSTRAINT prod_prov_not_ade_not_ade_fk FOREIGN KEY ( nota_adeudada_id,
                                                                     nota_adeudada_id_nota )
        REFERENCES nota_adeudada ( id,
                                   id_nota );

ALTER TABLE prod_prov_nota_ade
    ADD CONSTRAINT prod_prov_not_ade_prov_fk FOREIGN KEY ( prod_proveedor_id )
        REFERENCES prod_proveedor ( id );

ALTER TABLE prod_prov_nota_pag
    ADD CONSTRAINT prod_prov_nota_pagada_fk FOREIGN KEY ( nota_pagada_id_nota,
                                                                   nota_pagada_id )
        REFERENCES nota_pagada ( id_nota,
                                 id );

ALTER TABLE prod_prov_nota_pag
    ADD CONSTRAINT prod_prov_nota_pag_prov_fk FOREIGN KEY ( prod_proveedor_id )
        REFERENCES prod_proveedor ( id );

ALTER TABLE prov_prod_prov
    ADD CONSTRAINT prov_prod_prod_proveedor_fk FOREIGN KEY ( prod_proveedor_id )
        REFERENCES prod_proveedor ( id );

ALTER TABLE prov_prod_prov
    ADD CONSTRAINT prov_prod_prov_proveedor_fk FOREIGN KEY ( proveedor_id )
        REFERENCES proveedor ( id );

ALTER TABLE proveedor_carniceria
    ADD CONSTRAINT prov_carn_carn_fk FOREIGN KEY ( carniceria_id )
        REFERENCES carniceria ( id );

ALTER TABLE proveedor_carniceria
    ADD CONSTRAINT prov_carn_prov_fk FOREIGN KEY ( proveedor_id )
        REFERENCES proveedor ( id );


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0